### ISSUE TITLE
PostgreSQL version incompatibility in installer.sh

### ISSUE THREAD

**Issue by jppzanetti** [epos-eu/EOSC-ORFEUS_B2SAFE-docker#1]
During the setup, when the container is running [installer.sh, at lines 12 and 14](https://github.com/epos-eu/EOSC-ORFEUS_B2SAFE-docker/blob/4a2747a48120578a875b198b9657ec4cdb4bd22f/installer.sh#L12-L14), the following errors show up:

```
mv: cannot stat '/var/lib/postgresql/10/main/': No such file or directory
sed: can't read /etc/postgresql/10/main/postgresql.conf: No such file or directory
```

This is due to the fact that the PostgreSQL installed is version 11, so the correct directories would be `/var/lib/postgresql/11/` and `/etc/postgresql/11/`.

Is version 10 really needed, and then it would be necessary to direct `apt` to install it in the Dockerfile, or is it possible to just change installer.sh to point to these two directories?

**Comment by massimo1962** [comment]
it is ok just change the installer.sh; it is no mandatory the version 10.
