### ISSUE TITLE
What to install in Dockerfile and in installer.sh?

### ISSUE THREAD

**Issue by jppzanetti** [epos-eu/EOSC-ORFEUS_B2SAFE-docker#3]
While looking into how to clean up the code, I noticed that B2SAFE's `create_deb_package.sh` script is being run in both `Dockerfile` and `installer.sh`. Which one is the "better" place to do it?

More generally, how much of the installation should be run in the `Dockerfile`, and how much should be left to the `installer.sh` script?

**Comment by massimo1962** [comment]
As a general rule the best choice is run the installation as much as possible into dockerfile; but sometime it's not possible hence we use a shell script. The inconvenience that you describe it's due, probably, to a my distraction. So leave the install script run into Dockerfile; then we have to test it.

**Comment by jppzanetti** [comment]
Yes, as far as I could tell without running it over and over again, the rest of the B2SAFE and B2HANDLE setups require iRODS running, so they need to be in `installer.sh`. I'll try moving just the `create_deb_package.sh` to the `Dockerfile` and see what happens.
